from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from lab_platform.models import BackendProgress, BenchSnapshot, FirmwareInput


class LabBackend(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def list_benches(self) -> list[BenchSnapshot]: ...

    async def get_bench(self, bench_id: str) -> BenchSnapshot: ...

    async def power_on(self, bench_id: str) -> None: ...

    async def power_off(self, bench_id: str) -> None: ...

    async def power_cycle(self, bench_id: str) -> None: ...

    def flash_firmware(
        self, bench_id: str, firmware: FirmwareInput
    ) -> AsyncIterator[BackendProgress]: ...
